CREATE TABLE `t_dota_hero_info` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) DEFAULT NULL,
  `STRENGTH` int(11) DEFAULT NULL,
  `AGILITY` int(11) DEFAULT NULL,
  `INTELLIGENCE` int(11) DEFAULT NULL,
  `IS_CARRY` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;